PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

 select distinct ?subject ?label_en ?label_fr ?comment ?paper where{
 ?subject rdf:type ?object .
 ?subject rdfs:label ?label_en.
 ?subject rdfs:label ?label_fr.
 ?subject rdfs:comment ?comment.
 FILTER(LANGMATCHES(LANG(?label_en), "en"))
 OPTIONAL{FILTER(LANGMATCHES(LANG(?label_fr), "fr"))}
 OPTIONAL{ ?subject dc:description ?paper.}
 }
  ORDER BY ?subject