PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX m3: <http://sensormeasurement.appspot.com/m3#>
PREFIX iot-lite: <http://purl.oclc.org/NET/UNIS/fiware/iot-lite#>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT ?tesbed ?resource ?labelResource ?commentResource WHERE{

?testbed m3:hasM2MDevice ?resource.

	OPTIONAL{
		?resource rdfs:label ?labelResource.
	}
	
	OPTIONAL{
		?resource rdfs:comment ?commentResource.
	}

}



 

