PREFIX m3: <http://sensormeasurement.appspot.com/m3#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select distinct (count(?m2mAppli) as ?nbOntoDomain) where{
	?m2mAppli rdf:type m3:M2MApplication .
 	?m2mAppli m3:hasContext ?context .
}
