package fr.liris.cci.model;

// Generated Jan 14, 2013 12:41:23 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.synyx.hades.domain.Persistable;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable, Persistable<Long> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -472421046753892317L;
	
	private Long userId;
	private String name;
	private byte[] logo;
	private byte[] password;

	public User() {
	}

	public User(String name, byte[] logo, byte[] password) {
		this.name = name;
		this.logo = logo;
		this.password = password;
	}
	
	@Transient
	public boolean isNew() {
		return null == this.getId();
	}
	
	/**
	 * 
	 * @return
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_ID", unique = true, nullable = false)
	public Long getId() {
		return this.userId;
	}

	public void setId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "LOGO")
	public byte[] getLogo() {
		return this.logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	/**
	 * @return the password
	 */
	@Column(name = "PASSWORD")
	public byte[] getPassword() {
		return this.password;
	}

	/**
	 * @param password the password to set
	 */
	public void setPassword(byte[] password) {
		this.password = password;
	}
}