PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX m3: <http://sensormeasurement.appspot.com/m3#> 
PREFIX naturopathy: <http://sensormeasurement.appspot.com/naturopathy#> 
PREFIX nat: <http://sensormeasurement.appspot.com/naturopathy-dataset> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX food: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/food.owl#>
PREFIX recipe: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/recipes.owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX generic: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/generic.owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT ?m2mappli ?m2mdevice ?m2mapplilabel ?m2mapplicomment WHERE{
?m2mappli m3:hasM2MDevice ?m2mdevice.
?m2mappli m3:hasContext ?domain.
?m2mappli rdfs:label ?m2mapplilabel.
?m2mappli rdfs:comment ?m2mapplicomment.
FILTER(LANGMATCHES(LANG(?m2mapplilabel), "en"))
FILTER(LANGMATCHES(LANG(?m2mapplicomment), "en"))
}