PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX m3: <http://sensormeasurement.appspot.com/m3#> 
PREFIX naturopathy: <http://sensormeasurement.appspot.com/naturopathy#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX food: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/food.owl#>
PREFIX recipe: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/recipes.owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX generic: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/generic.owl#>


SELECT DISTINCT ?name ?value ?unit ?measurement ?inferType  ?deduce ?suggest WHERE{
?measurement m3:hasName ?name.
?measurement m3:hasValue ?value.
?measurement m3:hasDateTimeValue ?time.
?measurement m3:hasUnit ?unit.

?measurement rdf:type ?inferTypeUri.
OPTIONAL { ?inferTypeUri rdfs:label ?inferType. FILTER(LANGMATCHES(LANG(?inferType), "en"))}

?measurement naturopathy:hasColor ?colorUri.
?colorUri naturopathy:affectsOn ?emotionUri.

?emotionUri rdfs:label ?suggest.
?colorUri rdfs:label ?deduce.
FILTER(LANGMATCHES(LANG(?suggest), "en"))
FILTER(LANGMATCHES(LANG(?deduce), "en"))

 }
