PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX m3: <http://sensormeasurement.appspot.com/m3#> 
PREFIX naturopathy: <http://sensormeasurement.appspot.com/naturopathy#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX food: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/food.owl#>
PREFIX recipe: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/recipes.owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX generic: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/generic.owl#>


select distinct ?foodUri ?food_label_en ?disease ?diseaseUri where{

		?foodUri naturopathy:isRecommendedFor ?diseaseUri.
		?foodUri rdf:type naturopathy:Food.
		?diseaseUri rdfs:label ?disease.
		?foodUri rdfs:label ?food_label_en.
		FILTER(LANGMATCHES(LANG(?disease), "en"))
		FILTER(LANGMATCHES(LANG(?food_label_en), "en"))


}
