PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX naturopathy: <http://sensormeasurement.appspot.com/naturopathy#> 

select distinct ?foodUri ?food ?season ?seasonUri where{
?foodUri naturopathy:hasSeason ?seasonUri .
?foodUri rdfs:label ?food.
OPTIONAL  {?seasonUri rdfs:label ?season}.
FILTER ( lang(?food) = "en" )
 }