PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX food: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/food.owl#>
PREFIX recipe: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/recipes.owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX generic: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/generic.owl#>

SELECT DISTINCT  ?recipe ?recipeLabel ?r ?portion ?quantity ?ingt{
?r food:hasIngredient ?portion .
?portion generic:hasQuantity ?quantity .
?portion generic:madeOfSubstance ?ingt .
?recipe food:producesFoodItem ?r.
?recipe rdfs:label ?recipeLabel.

FILTER regex(str(?ingt), ?ingtUser, "i")

}

ORDER BY ?recipe