PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX stac: <http://securitytoolbox.appspot.com/stac#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 

select distinct ?subject ?label ?comment where{
	?object stac:satisfies ?subject.
	?subject rdfs:label ?label.
 	?subject rdfs:comment ?comment.
 	
OPTIONAL {
?object stac:isComposedOf ?a.
?a rdfs:subClassOf stac:SecurityPropertyMethod
?a stac:satisfies ?s
}
 }